#+HTML_HEAD: <link rel="stylesheet" href="../asset/css/page.css" type="text/css" media="screen" />
#+title: 沒錯，然而道存在嗎？

- 沒錯，然而道存在嗎？

- 唉，唉，你爲何如此固執！好吧，讓我稍微多談談這個問題。
- 道家不像西方的不可知論者一樣。那些人承認或者不承認上帝的存在，但他們其實不知道哪個結論對。西方的不可知論者會說，“由簡單的亞裏士多德式邏輯，就能明了，不管上帝存在與否，我們都沒有確切證據證明。因此，唯一理性的辦法，就是暫緩判斷這個問題，直到更進一步的證據出現。”反之，道教徒以完全不同的方式看待此問題。他不會“暫緩判斷”道是否存在的問題；他根本不會提出“道是否存在”這個問題，或者說，就算有人問他，他也會認爲，這個問題本身是含糊、沒有意義的，某種程度上是不着邊際和莫名其妙的。在這方面，他與西方的邏輯實證主義者不謀而合，雖然也許出於不同的理由。假設你問一個邏輯實證主義者“道是否存在”，他會宣稱這個問題“沒有意義”。他會首先考慮給“道”下一個明確的定義。如此，如果就像邏輯實證主義者所說那樣，這個問題是無意義的話，我將很高興地回答，“如果問題本身沒有意義可以免去不少麻煩的話，我們就不用費力去探尋什麼意義了。”
- 對此，你可能會有點惱火，並且表示說，“別回避問題！道到底存不存在？道究竟是某種真實的東西，還是其僅僅只是幻想——一種想象的虛構？”
- 好吧，類似的關於“存在”的問題在其他領域也已被問出，而且也一樣沒什麼用處。已經有更加形而上的問題，譬如說，所謂共性的存在——比如紅色，三角形，美麗，善良之類的。“紅色”存在嗎？如果答案是肯定的，那麼，它在哪兒？它多重？它長什麼形狀？什麼顏色？（你回答說“紅色”本身是紅的？不見得吧！）“紅色”到底存在不存在？有人可能會天真地回答，“紅色當然存在啦；看看玫瑰花，口紅，某些蘋果，等等等等……”然而，這只不過意味着，確實存在着某些東西是紅色的，卻不能證明所謂的“紅色”實體的存在。關於存在的實在性的問題的討論，在西方哲學史上一直相當活躍。所謂唯名論者相信，這個問題的答案是否定的。當然，他們承認，存在着特定的紅色物體，但他們否認“紅”的實體的存在。他們接受“色”的形容詞用法（因爲確實有紅色的東西），然而徹底否認將“紅”本身用作名詞的行爲。他們認爲“紅”這一名詞沒有任何實際的意義；他們不相信作爲名詞的“紅”能夠指代任何東西。此外，也有一些所謂的“唯實論者”（或曰“柏拉圖主義者”），覺得作爲名詞的“紅”的的確確是一個合法的名詞——它指代了實體的“紅色”。他們也相信，“紅”這個詞既可以作形容詞，也可以作名詞。比如說，像“這個蘋果是紅的”這句話，其中的“紅”就是形容詞；像“紅是三原色之一”這句話，其中的“紅”就是名詞。唯實論者認爲，“紅”確實是一個名字，它是紅顏色的名字。
- 與此相似，唯名論-唯實論之間的爭論也延伸到了其他所謂的“普遍性”上。唯實論者，比如柏拉圖，相信“美”，“善”，“真理”，都是存在的；唯名論者卻僅僅認爲，某些藝術品是“美”的，某些行爲是“善”的，某些命題可以被適當地標記爲“真”的。
- 可能會讓某些非數學專業的讀者驚訝的是，即使是在數學基礎領域，也存在這種爭論。外行人會誤解這一領域是確定的、非爭議性的。但是這可謂謬之千里！有一種所謂數學“唯實論者”（或者說古典主義者，柏拉圖主義者），他們認爲，在非語言的數學實體，譬如“數字、集合、函數、羣、拓撲空間……等等”的世界中，是數學的宗旨發現並證明了這些陳述，表明了這些實體的真實性。另一方面，還有所謂的數學“形式主義者”，他們相信這些所謂的數學實體完全出自想象力的虛構；唯一的現實，是用來表達他們的符號本身！所以，數學形式主義的興趣似乎是純粹的語言學。對這些人而言，數學是一種關於所謂“正規表達式”的字符串是如何根據被研究的系統的規則被操作的研究；表達式本身並不表達任何東西！而且，形式主義者（類似唯名論者）否認像“數”這樣的概念有語言表達之外的意義存在。
- 我們似乎接近道的存在問題了。大概有人否認“道”作爲一個名詞的用法；他們拒絕承認存在名爲道的“實體”，但是他們會承認作爲形容詞的“道家的”一詞的意義。所有學習中國藝術的學生（即使是那些絕對不做任何意義上的形而上學討論的）都會明顯地做出判斷，某件藝術品相對擁有更多的道家特徵。比如，人們普遍認爲，宋代山水畫比唐代藝術更有道家氣息。因此，很少有人反對使用“道家的”這一形容詞，盡管許多人可能會反對使用名詞“道”。
- 你們有些人可能依然認爲，我在回避道真實存在與否的問題。其實呢，我知道這個問題的答案嗎？你可能會回復我說：“你甚至根本沒有關於這個問題的個人觀點吧？”
- 假設，你已經把我逼到了我書房的角落裏，命令我要直截了當地回答問題。“薩繆里安！不要再含糊其辭了！你覺得道到底存不存在？”我該怎麼回答才好呢？這將取決於，你問我問題的時候，我身處的語境更偏向於西方還是東方。如果我身處的語境更爲西方式（遵守存在-不存在的二元對立），那麼，因爲我更傾向於柏拉圖主義，我可能會回答：“沒錯，道存在。”但是假如我身處東方式的語境中呢？好了，想想看，你問一個禪師，道是否存在，那他可能會給你來個當頭棒喝。不過我現在情緒比較溫和，可能只是給你個微笑吧（沒準兒會有點居高臨下），並且給你沏杯茶。
