#+HTML_HEAD: <link rel="stylesheet" href="../asset/css/page.css" type="text/css" media="screen" />
#+title: 道是無形的
- 1、道可以被定義嗎？
- 禪宗或許可以被恰當地描述爲：中國道教的胡椒粉和印度佛教的鹽被日本人混爲一體（胡椒粉尤其多）。值得懷疑的是，禪宗佛教是否該被稱爲哲學。許多禪宗的追隨者一再強調，與一套有認知意義的命題相比，禪宗更多的是一種生活方式，一系列態度，一組確定的經驗。我覺得這種說法很有道理，但像很多其他的說法一樣，也可能是言過其實了。我確實認爲禪是一種“途”，而非某種“主義”，但我不覺得禪完全缺乏主義。而且，在我看來，被禪宗明確強調的事情之一是，超驗的觀念具有內在的正確性；確定的是，超驗與內在是一致的。這一節禪經中最明確地對此進行了表達：
- 野禽啼枝頭，聲攜杜宇事。
- 山花爛漫時，意帶其香息。
- 而且，在一則著名的禪宗問答中，“超驗性是內在的”這一點已經明之又明。有人問禪師，“道是什麼？”禪師答道：“是你每日所思”。
- 有人可能會問，“如果道只不過是人的每日所思，那爲什麼要稱其爲道；爲什麼不直接叫它‘每日所思’？”
- 要遵守邏輯地回答這個問題是極度困難的。首先，我認爲，說“道是你每日所思”意味着“道只不過是你的每日所思”是一種錯誤的闡釋。我幾乎認爲，在“道是你每日所思”這句話中，“是”這個字的作用是將“道”和“每日所思”置於平等的位置上。我寧願說，道是你的每日所思以及更多。其實，在關於道的著作中，道是早於天地的。所以，你的頭腦先於天地而存在嗎？也許真的是這樣，不過誰知道呢？無論如何，我發現，“道是你每日所思”這個說法，非常有啓發性。當然，不能想得太過死板。
- 然而，你也許會繼續問，如果道僅僅是某人的每日所思，爲什麼不直接叫它“每日所思”，卻還要稱其爲道？而且。還是那個問題，究竟什麼是道，該如何定義道？
- 文字已經以很多不同的方式被翻譯表達了。上帝、自然、絕對、一切事物存在的基礎、太虛、途徑、道路，等等。也許我最喜歡的一個定義是：“讓事物成爲事物的理由”。但我要問：對於這些定義而言——愉快與啓發性的定義——真的能澄清道的概念嗎？而且更進一步地，真的有必要澄清這個概念嗎？
- 有人說，“道”一詞是不可翻譯的；還有人說，道是不可定義的。第一個說法令人奇怪嗎？你們之中，有誰知道一門外語之中，有些詞匯只能用英文進行近似表達，卻無法找到對應概念的？現在讓我們考慮“道是不可定義的”這個說法。這引起了很多以“思想者”的身份自豪的人的嚴重懷疑。但這樣的懷疑正確嗎？很多人會武斷魯莽地說，除非一個人可以定義其術語，否則人根本不知道人在說些什麼。沒錯，確實有奇怪的說法認爲，無法界定一個人話語的含義，只不過意味着話語沒有意義。我覺得，對於這一點，我們應該參考哲學家維特根斯坦明智的話語：“不要尋找意義，要尋找使用！”這可能是這一問題的關鍵。雖然我還可以更進一步，說意義就是使用——至少真正的意義就是使用。對我而言，一個術語的真正含義是其所有用途的總和、以及人們對術語的所有聯想。這些怎麼能在一個短短的定義中全被包含呢？因此，我認爲，如果你真的想找到像“道”這類詞的真意——如同那些道書作者使用這個詞時的意義——你不可能指望一個像“定義”這樣的捷徑。爲了理解“道”這一術語的真正含義，必須要在其千萬種使用方式裏取樣。但這還不夠。要理解道這一概念，還必須精通道的書畫（也許甚至還有書法）——在這些作品中，道的感覺已經得到具體傳神的體現。總之，要理解“道”，必須徹底浸淫於道的哲學與藝術之中。
- 在你完成這些之後，在你已經將數千種“道”一詞的用法採樣之後，你也許可以試試，聰明地爲這些不同的例子總結一個單一的定義出來。但是，就算你成功了，你的定義對於那些沒有體驗過你那些活生生的經歷的人來說，只不過是絕對的空殼！
- 2、道在何種意義上是真實的？
- 有人可能會聲稱，道只能通過神祕體驗才能被了解。那麼神祕體驗到底是什麼？幾乎無人不知審美經驗的含義，但是神祕體驗又是什麼呢？它們可能是相關的，不過我不覺得它們相同。對我而言，神祕體驗與審美經驗的區別，就像它於幽默感的區別一樣。
- 但神祕感是什麼？神祕體驗又是什麼？是一種浮動不定的經驗？還是某種什麼東西的經驗？如果是某種什麼東西的經驗，那這種東西是現實的還是只存在於想象之中？
- 這個問題始終伴隨着如此巨大的爭議！很多神祕主義心理學家做了各種長度的證明，表明神祕體驗不是什麼真實的體驗。他們描繪道，神祕就像那些情緒不安的人一樣（通常是精神分裂症或者歇斯底裏症），這些人將他們在真實世界中找不到的東西轉移到了其想象世界。另一方面，神祕主義的維護者（通常是哲學家，而非真正的神祕主義者）用了同樣篇幅的證明，試圖說服我們，神祕主義者的感覺確實是真實的。那麼，誰才是正確的？神祕感知究竟是真是假？
- 好了，現在假設有兩個人，有一個是音樂家，另一個對音樂一竅不通。他們正在聽同一主題。不懂音樂的人坦言，“我聽到音符，但沒聽到旋律”。音樂家則信誓旦旦地說，他聽到了更重要的東西——旋律！那麼，這個音樂家聽到的“旋律”到底是什麼？記錄本身——聲波——在物理意義上，公認地，是被音樂家和不懂音樂的人以同樣的方式聽到的。那麼，旋律本身到底是什麼呢？它是真實的，還是只存在於意識或者想象之中？真是奇怪的問題！我認爲，說它只存在於想象之中，是一種嚴重的誤導；音樂家說，他聽到了旋律，這不僅僅是只存在於想象中的東西。不，聽到的旋律的的確確是現實的，盡管說它是否存在於腦海中是一個更加微妙的問題，是我不能回答的問題。無論如何，我覺得，當我說“旋律是真實的”時，沒有多少人會不同意。我認爲，談論道是否是真實的這個問題，更是類似如此。真正的道教徒（或者信奉其他宗教的神祕主義者，乃至無神論神祕主義者）直接感知他們所謂的道（或者上帝、自然、絕對、宇宙意識），就像音樂家直接感知旋律一樣。音樂家不需要對旋律的存在有“信心”，也不需要依據聖經來確定旋律的存在；他顯然擁有關於旋律的直接經驗。一旦聽到旋律，就不可能再對其生疑。
- 道究竟是怎麼被直接感知的呢？嗯，旋律是如何被直接感知的呢？通過聽感？不全是吧！物理層面上的聆聽過程顯然起到了必要的作用，但這並不是事情的全部。不懂音樂的人的聽力可能像音樂家一樣好，然而音樂家體驗了不懂音樂的人聽不到的旋律。所以，我們在說“聽旋律”的時候對“聽”字的使用，與我們說“聽聲音”的時候相比，涉及到更加廣泛與微妙的意義。關鍵是，“旋律”不僅僅只是一組聲音；“旋律”意味着聲音具有某種共同的模式，或曰某種意義上的上層結構。
- 大概有人會說，道無非是物理宇宙罷了。這說法就像聲音與旋律一樣，也缺失了類似的關鍵點。按照這種說法，旋律也無非只是一組聲音罷了。與此相比，不如說，宇宙承擔了等同於道的分類關系，就像對旋律的記錄承擔了旋律本身一樣。
